export enum Technology {
	JavaScript = "JavaScript",
	TypeScript = "TypeScript",
	Java = "Java",
	Python = "Python",
	Ruby = "Ruby",
	CSharp = "C#",
	Go = "Go",
	Rust = "Rust",
	Swift = "Swift",
	Kotlin = "Kotlin",
	Scala = "Scala",
	PHP = "PHP",
	CPlusPlus = "C++",
	C = "C",
	Haskell = "Haskell",
	Lua = "Lua",
	Perl = "Perl",
	R = "R",
	Shell = "Shell",
	SQL = "SQL",
	Git = "Git",
	Docker = "Docker",
	Kubernetes = "Kubernetes",
	Jenkins = "Jenkins",
	GitHubActions = "GitHub Actions",
}
